apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestifined-ms-framework
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: nestifined-ms-framework
          resources:
            limits:
              memory: '256Mi'
              cpu: '250m'
            requests:
              memory: '128Mi'
              cpu: '125m'
