apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestifined-ms-framework
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: nestifined-ms-framework
          resources:
            limits:
              memory: '512Mi'
              cpu: '500m'
            requests:
              memory: '256Mi'
              cpu: '250m'
