bases:
  - ../base

namespace: nestifined-staging

resources:
  - namespace.yaml

patchesStrategicMerge:
  - deployment.yaml

configMapGenerator:
  - name: nestifined-ms-framework-config
    literals:
      - NODE_ENV=staging
