namespace: nestifined-staging
resources:
  - namespace.yaml
  - ../base
  - secrets.yaml
configMapGenerator:
  - name: nestifined-ms-framework-config
    behavior: merge
    literals:
      - NODE_ENV=staging
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: deployment.yaml
